### ISSUE TITLE
common container name = multiples builds on same container?

### ISSUE THREAD

**Issue by juju4** [bradenwright/kitchen-lxd_cli#6]
Hello

As said, I'm working on jenkins with ansible and lxd. while having 2 jobs running and checking lxc list, I observe that there is only one container whereas 2 jobs running on same system. 
Also got job interrupted by halt message.

```
06:25:53        TASK [initcfg : Debian | Extra packages install] *******************************
06:26:02        
06:26:02        Broadcast message from root@default-ubuntu-1204
06:26:02        	(unknown) at 10:26 ...
06:26:02        
06:26:02        
The system is going down for halt NOW!
06:26:02        SIGPWR received 
06:26:02 D      Cleaning up local sandbox in /tmp/default-ubuntu-1204-sandbox-20160801-26173-wllkhn
06:26:02 >>>>>> ------Exception-------
06:26:02 >>>>>> Class: Kitchen::ActionFailed
06:26:02 >>>>>> Message: 3 actions failed.
06:26:02 >>>>>>     Converge failed on instance <default-ubuntu-1604>.  Please see .kitchen/logs/default-ubuntu-1604.log for more details
06:26:02 >>>>>>     Converge failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
06:26:02 >>>>>>     Failed to complete #converge action: [closed stream] on default-ubuntu-1204
```

It would be nice for kitchen-lxd to generate a unique container name per test & platform in order to avoid conflicts. test name can still be default-distribution-version but behind the scene should be different per job.
Or maybe are you nesting some containers? I view active process of containers on host but files linked to a job seems to have only temporary life on active containers. Always have the same
```
# lxc list
+---------------------+---------+--------------------------------+------+------------+-----------+
|        NAME         |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+---------------------+---------+--------------------------------+------+------------+-----------+
| default-ubuntu-1404 | RUNNING | 10.252.116.82 (eth0)           |      | PERSISTENT | 0         |
+---------------------+---------+--------------------------------+------+------------+-----------+
| default-ubuntu-1604 | RUNNING | 10.252.116.1 (lxdbr0)          |      | PERSISTENT | 0         |
|                     |         | 10.252.116.28 (eth0)           |      |            |           |
+---------------------+---------+--------------------------------+------+------------+-----------+
```

Also an option so container are deleted or frozen at the end of the test even after failure would be nice to avoid resources exhaustion.
current default is good as it allow quick manual check after test execution.

Comments?

Thanks

**Comment by bradenwright** [comment]
So the best I could come up with for now is to append the epoch time at the end of the instance name.  I figure epoch time should be unique.  In order to not create new instances all the time I had to write it out to a file in .kitchen/<instance name>.lxd

Look over https://github.com/bradenwright/kitchen-lxd_cli/tree/issue-6 and let me know that this suits your needs.  Or if you have any improvements/suggestions

**Comment by juju4** [comment]
epoch is fine for me. for clarity, maybe adding rolename inside would be useful.
it builds fine as below.
so far, so good. kitchen test/verify/destroy ok

```
$ git clone https://github.com/bradenwright/kitchen-lxd_cli.git
$ cd kitchen-lxd_cli/
$ git checkout issue-6
$ gem build kitchen-lxd_cli.gemspec 
WARNING:  WARNING: license value 'Apache 2.0' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  description and summary are identical
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 0'
[...]
$ gem install kitchen-lxd_cli-2.0.1.gem --user
WARNING:  You don't have /var/lib/jenkins/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Successfully installed kitchen-lxd_cli-2.0.1
Parsing documentation for kitchen-lxd_cli-2.0.1
Installing ri documentation for kitchen-lxd_cli-2.0.1
Done installing documentation for kitchen-lxd_cli after 0 seconds
1 gem installed
```

**Comment by bradenwright** [comment]
More than to accept a pr, or add something for a role name.  I guess best I could think is I made a config attribute 'lxd_unique_name' so maybe something like if that were not true or false but a string then use that as the name for the container.  Otherwise tell me what you mean by rolename or what your use case is.

I'm gonna close the ticket, I just publish the gem with the changes, but feel free to comment further/reopen/etc.  Just closing b/c as of now its at least not an issue.
