### ISSUE TITLE
misleading message - "#config[:public_key_path] cannot be blank"

### ISSUE THREAD

**Issue by juju4** [bradenwright/kitchen-lxd_cli#7]
When using an account where there is no existing ssh key, kitchen-lxd_cli returns

```
Kitchen::Driver::LxdCli<default-ubuntu-1604>#config[:public_key_path] cannot be blank
```

Message is misleading you to review .kitchen.yml, while you only need to ssh-keygen on account calling kitchen.
Also, like vagrant, I think it would be better if plugin was using its own temporary ssh key (one per container) instead of user one to ensure thing are separated and not mixing testing and production keys.

**Comment by bradenwright** [comment]
That error message could definitely be better.  I'll definitely update the message.  

Personally I think I prefer checking default locations for an ssh key, although I'd be fine having an option to auto generate one, or to autogen an a

**Comment by bradenwright** [comment]
I didn't really like the idea of generating someones public key from a security stand point.  If you feel differently I'd be willing to autogenerate it and have a config option to turn on/off auto generating.  But I give the command in the output.  Just there are decisions of what size key, etc.  

Always open to suggestions, maybe there is a use case where you want it automated, which I can always appreciate.  I'm closing but feel free to reopen if you want.

I'll make sure to release this soon to rubygems but its merged into master.

**Comment by juju4** [comment]
clearly, agree on user ssh key generation.
I was more suggesting one limited to kitchen instance like vagrant is doing (not the insecure key but the randomized/temporary one)
