### ISSUE TITLE
container not stopping: force ?

### ISSUE THREAD

**Issue by juju4** [bradenwright/kitchen-lxd_cli#8]
Hello Braden,

small issue. most of the time my container are not easily stopped and kitchen stalled there.
I just edit lxd_cli.rb to add --force.

Either do that, either a timeout because else, it seems to last indefinitely.

Thanks

**Comment by bradenwright** [comment]
I'm good with force stopping, I'll put it in now

**Comment by bradenwright** [comment]
Merged into master, I'll release to rubygems soon.  Hopefully I can knock off another issue or 2 first
